# Rustfmt configuration for envcheck
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments  
normalize_comments = true
wrap_comments = true
comment_width = 100

# Formatting
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true

# Functions
fn_params_layout = "Tall"
fn_single_line = false

# Control flow
match_block_trailing_comma = true

# Structs
struct_lit_single_line = true
